Graceful transition to asyncio.all_tasks
P403n1x87/austin-tui pull request #4
Opened 2020-10-27 16:40 UTC by cool-RR

This prevents a `DeprecationWarning` shown in Python 3.8.

2020-10-28 14:34 UTC, P403n1x87 requested changes
Thanks for your contribution. I have left some review comments for you 😄

2020-10-28 14:34 UTC, P403n1x87 commented on austin_tui/__main__.py
> +    get_all_tasks = asyncio.Task.all_tasks # Python 3.6 compatibility
The project uses Black as the default formatter so could you please:
- leave two blank lines before and after this block
- leave two spaces before starting an inline comment

Could you also rename `get_all_tasks` into `_get_all_tasks` as this is just a local alias.

Cheers!

2020-10-28 14:40 UTC, cool-RR commented
Fixed.

2020-10-28 15:52 UTC, cool-RR commented
Tests are failing with "ModuleNotFoundError: No module named 'distutils.spawn'". Is this related to my change?

2020-10-28 15:55 UTC, P403n1x87 commented
> 
> 
> Tests are failing with "ModuleNotFoundError: No module named 'distutils.spawn'". Is this related to my change?

No, that I believe is caused by poetry and Python 3.9. However, the linter errors need to be addressed

~~~
austin_tui/__main__.py:37:5: W291 trailing whitespace
austin_tui/__main__.py:42:1: W293 blank line contains whitespace
~~~

2020-10-28 16:00 UTC, cool-RR commented
Fixed.

2020-10-29 07:04 UTC, cool-RR commented
Now does the lint pass? I can't find where the failure is supposed to show.

2020-10-29 09:08 UTC, P403n1x87 commented
> 
> 
> Now does the lint pass? I can't find where the failure is supposed to show.

Linter is good now (https://travis-ci.org/github/P403n1x87/austin-tui/builds/739657303). The job is still failing because nox cannot create the Python 3.9 venv. I'm trying to fix this but the annoying thing is that it works perfectly fine on my Ubuntu 18.04 so don't really know what needs to be fixed.

2020-10-29 10:31 UTC, merged